### ISSUE TITLE
Question: Which org-modern fonts are you based

### ISSUE THREAD

**Issue by yanboyang713** [hieutkt/dotfiles#1]
Hello,

Good day to you.

I want to using your org-modern config. Looks great.

https://github.com/hieutkt/dotfiles/blob/main/emacs/.doom.d/config.org#3132-org-modern

However, I could NOT display **org-modern-radio-target**, **org-modern-star**, and **org-modern-keyword** correctly.

May I ask, which front does this three symbol your based on?

Thanks for your time.

**Comment by hieutkt** [comment]
Hi,

I was not super careful about font availability when choosing these symbols. For me like the star symbol and the internal target are displayed by Alegreya Sans (my variable width font), the radio target fallback to Noto Sans installed on my system, the keyword symbol is displayed by Sarasa Mono (my mono font).

Here's what they look like for me:

![image](https://user-images.githubusercontent.com/16746470/210901648-66a352fb-ecd1-4374-904b-7e172fe3c709.png)

**Comment by yanboyang713** [comment]
Hello @hieutkt ,

ok, got you.

Thanks so much
